"""Export functionality for 3D scenes to glTF and OBJ formats."""

import os
from pathlib import Path
from typing import Dict, Optional

import numpy as np
import trimesh

from .types import Mesh3D, Scene3D


class SceneExporter:
    """Exports Scene3D to various file formats."""

    # Default material colors for visualization
    DEFAULT_MATERIALS: Dict[str, tuple] = {
        "wall_exterior": (0.8, 0.75, 0.7, 1.0),  # Light tan
        "wall_interior": (0.95, 0.95, 0.92, 1.0),  # Off-white
        "floor_default": (0.6, 0.5, 0.4, 1.0),  # Wood brown
        "ceiling_default": (1.0, 1.0, 1.0, 1.0),  # White
        "door_frame": (0.4, 0.3, 0.2, 1.0),  # Dark wood
        "door_panel": (0.5, 0.4, 0.3, 1.0),  # Medium wood
        "window_frame": (0.3, 0.3, 0.3, 1.0),  # Dark gray
        "glass": (0.7, 0.85, 0.95, 0.3),  # Light blue transparent
        "default": (0.5, 0.5, 0.5, 1.0),  # Gray
    }

    def __init__(self, include_materials: bool = True):
        self.include_materials = include_materials

    def export_gltf(
        self, scene: Scene3D, path: str, binary: bool = True
    ) -> Optional[str]:
        """
        Export scene to glTF/GLB format.

        Args:
            scene: The Scene3D to export
            path: Output file path (.glb or .gltf)
            binary: If True, export as binary GLB

        Returns:
            The exported file path, or None if export failed
        """
        trimesh_scene = self._build_trimesh_scene(scene)

        if len(trimesh_scene.geometry) == 0:
            return None

        # Ensure directory exists
        Path(path).parent.mkdir(parents=True, exist_ok=True)

        file_type = "glb" if binary else "gltf"
        trimesh_scene.export(path, file_type=file_type)

        return path

    def export_obj(self, scene: Scene3D, path: str) -> Optional[str]:
        """
        Export scene to OBJ format with MTL material file.

        Args:
            scene: The Scene3D to export
            path: Output file path (.obj)

        Returns:
            The exported file path, or None if export failed
        """
        all_meshes = scene.get_all_meshes()

        if not all_meshes:
            return None

        # Ensure directory exists
        Path(path).parent.mkdir(parents=True, exist_ok=True)

        # Combine all meshes
        trimeshes = []
        for mesh in all_meshes:
            if mesh.vertices.size > 0:
                tm = mesh.to_trimesh()
                if self.include_materials:
                    color = self.DEFAULT_MATERIALS.get(
                        mesh.material_id, self.DEFAULT_MATERIALS["default"]
                    )
                    tm.visual = trimesh.visual.ColorVisuals(
                        mesh=tm, face_colors=[color] * len(tm.faces)
                    )
                trimeshes.append(tm)

        if not trimeshes:
            return None

        combined = trimesh.util.concatenate(trimeshes)
        combined.export(path, file_type="obj")

        # Write MTL file
        self._write_mtl_file(scene, path)

        return path

    def _build_trimesh_scene(self, scene: Scene3D) -> trimesh.Scene:
        """Build a trimesh Scene with organized node hierarchy."""
        trimesh_scene = trimesh.Scene()

        for element_type, meshes in scene.meshes.items():
            if not meshes:
                continue

            # Combine meshes of same type
            trimeshes = []
            for mesh in meshes:
                if mesh.vertices.size > 0:
                    tm = mesh.to_trimesh()
                    if self.include_materials:
                        color = self.DEFAULT_MATERIALS.get(
                            mesh.material_id, self.DEFAULT_MATERIALS["default"]
                        )
                        tm.visual = trimesh.visual.ColorVisuals(
                            mesh=tm, face_colors=[color] * len(tm.faces)
                        )
                    trimeshes.append(tm)

            if trimeshes:
                combined = trimesh.util.concatenate(trimeshes)
                trimesh_scene.add_geometry(combined, node_name=element_type)

        return trimesh_scene

    def _write_mtl_file(self, scene: Scene3D, obj_path: str) -> None:
        """Write a companion MTL file for OBJ export."""
        mtl_path = obj_path.rsplit(".", 1)[0] + ".mtl"

        # Collect unique material IDs
        material_ids = set()
        for meshes in scene.meshes.values():
            for mesh in meshes:
                material_ids.add(mesh.material_id)

        with open(mtl_path, "w") as f:
            f.write("# Material file generated by ArchViz AI\n\n")

            for mat_id in sorted(material_ids):
                color = self.DEFAULT_MATERIALS.get(
                    mat_id, self.DEFAULT_MATERIALS["default"]
                )
                r, g, b, a = color

                f.write(f"newmtl {mat_id}\n")
                f.write(f"Kd {r:.3f} {g:.3f} {b:.3f}\n")  # Diffuse color
                f.write(f"Ka {r*0.1:.3f} {g*0.1:.3f} {b*0.1:.3f}\n")  # Ambient
                f.write("Ks 0.1 0.1 0.1\n")  # Specular
                f.write("Ns 10.0\n")  # Shininess

                if a < 1.0:
                    f.write(f"d {a:.3f}\n")  # Transparency

                f.write("\n")


def export_scene(
    scene: Scene3D,
    output_dir: str,
    name: str = "model",
    formats: list = None,
) -> Dict[str, str]:
    """
    Convenience function to export scene to multiple formats.

    Args:
        scene: The Scene3D to export
        output_dir: Output directory
        name: Base filename without extension
        formats: List of formats to export ("glb", "gltf", "obj")

    Returns:
        Dict mapping format to exported file path
    """
    if formats is None:
        formats = ["glb", "obj"]

    exporter = SceneExporter()
    results = {}

    for fmt in formats:
        if fmt == "glb":
            path = os.path.join(output_dir, f"{name}.glb")
            result = exporter.export_gltf(scene, path, binary=True)
            if result:
                results["glb"] = result
        elif fmt == "gltf":
            path = os.path.join(output_dir, f"{name}.gltf")
            result = exporter.export_gltf(scene, path, binary=False)
            if result:
                results["gltf"] = result
        elif fmt == "obj":
            path = os.path.join(output_dir, f"{name}.obj")
            result = exporter.export_obj(scene, path)
            if result:
                results["obj"] = result

    return results
